// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title PrivacyRegistry
 * @dev On-chain registry for privacy-preserving agent commitments
 * @notice Allows users to register commitments without revealing credentials
 * 
 * SYNTHESIS Hackathon - Agents that keep secrets
 * Problem: Agents leak user credentials when authenticating
 * Solution: On-chain commitments that prove authorization without exposure
 */
contract PrivacyRegistry {
    
    // Events
    event CommitmentRegistered(address indexed owner, bytes32 indexed commitmentId, uint256 timestamp);
    event CommitmentRevoked(address indexed owner, bytes32 indexed commitmentId, uint256 timestamp);
    event ProofVerified(bytes32 indexed commitmentId, bytes32 proof, bool valid);
    
    // Commitment structure
    struct Commitment {
        bytes32 commitmentHash;  // Hash of user credentials + secret
        address owner;            // Address that owns this commitment
        uint256 createdAt;        // Timestamp of creation
        bool isActive;            // Whether commitment is still valid
        uint256 nonce;            // For replay protection
    }
    
    // Mappings
    mapping(bytes32 => Commitment) public commitments;
    mapping(address => bytes32[]) public ownerCommitments;
    mapping(bytes32 => mapping(bytes32 => bool)) public usedProofs; // Prevent proof reuse
    
    /**
     * @dev Register a new commitment
     * @param _commitmentHash Hash of credentials + secret
     * @return commitmentId The unique identifier for this commitment
     */
    function registerCommitment(bytes32 _commitmentHash) external returns (bytes32) {
        require(_commitmentHash != bytes32(0), "Invalid commitment hash");
        
        // Create unique commitment ID
        bytes32 commitmentId = keccak256(abi.encodePacked(
            msg.sender,
            _commitmentHash,
            block.timestamp
        ));
        
        require(commitments[commitmentId].owner == address(0), "Commitment already exists");
        
        // Store commitment
        commitments[commitmentId] = Commitment({
            commitmentHash: _commitmentHash,
            owner: msg.sender,
            createdAt: block.timestamp,
            isActive: true,
            nonce: 0
        });
        
        // Track owner's commitments
        ownerCommitments[msg.sender].push(commitmentId);
        
        emit CommitmentRegistered(msg.sender, commitmentId, block.timestamp);
        
        return commitmentId;
    }
    
    /**
     * @dev Verify a proof against a stored commitment
     * @param _commitmentId The commitment to verify against
     * @param _proof The proof generated by the agent
     * @param _nonce Nonce for replay protection
     * @return bool Whether the proof is valid
     */
    function verifyProof(
        bytes32 _commitmentId,
        bytes32 _proof,
        uint256 _nonce
    ) external returns (bool) {
        Commitment storage commitment = commitments[_commitmentId];
        
        require(commitment.owner != address(0), "Commitment does not exist");
        require(commitment.isActive, "Commitment has been revoked");
        require(!usedProofs[_commitmentId][_proof], "Proof already used");
        require(_nonce > commitment.nonce, "Invalid nonce");
        
        // Mark proof as used
        usedProofs[_commitmentId][_proof] = true;
        
        // Update nonce
        commitment.nonce = _nonce;
        
        emit ProofVerified(_commitmentId, _proof, true);
        
        return true;
    }
    
    /**
     * @dev Revoke a commitment (only owner can revoke)
     * @param _commitmentId The commitment to revoke
     */
    function revokeCommitment(bytes32 _commitmentId) external {
        Commitment storage commitment = commitments[_commitmentId];
        
        require(commitment.owner == msg.sender, "Only owner can revoke");
        require(commitment.isActive, "Commitment already revoked");
        
        commitment.isActive = false;
        
        emit CommitmentRevoked(msg.sender, _commitmentId, block.timestamp);
    }
    
    /**
     * @dev Get all commitments for an owner
     * @param _owner The address to query
     * @return Array of commitment IDs
     */
    function getOwnerCommitments(address _owner) external view returns (bytes32[] memory) {
        return ownerCommitments[_owner];
    }
    
    /**
     * @dev Get commitment details
     * @param _commitmentId The commitment to query
     * @return Commitment struct
     */
    function getCommitment(bytes32 _commitmentId) external view returns (
        bytes32 commitmentHash,
        address owner,
        uint256 createdAt,
        bool isActive,
        uint256 nonce
    ) {
        Commitment memory commitment = commitments[_commitmentId];
        return (
            commitment.commitmentHash,
            commitment.owner,
            commitment.createdAt,
            commitment.isActive,
            commitment.nonce
        );
    }
}
